name: Deploy Angular App to Azure

on:
  push:
    branches:
      - main  # Change to your branch if needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.20.4'  # Change to your Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build Angular app
      run: npm run build --prod

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: angular-dist
        path: dist/Frontend  # Change this to your Angular output folder

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: "TimeSnaper"  # Replace with your Azure App Service name
        package: dist/Frontend  # Change to match your Angular build output
