name: Deploy Angular App to Azure

on:
  push:
    branches:
      - main  # Change to your branch if needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.20.4'  # Node 18 is recommended for Angular

    - name: Install dependencies
      run: npm ci  # Faster & better than "npm install"

    - name: Build Angular app
      run: npm run build -- --configuration=production  # Use "--configuration=production" instead of "--prod"

    - name: Upload build artifact
      uses: actions/upload-artifact@v4  # Updated to v4
      with:
        name: angular-dist
        path: dist/Frontend  # Change if your build output directory is different

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: "TimeSnaper"  # Replace with your Azure App Service name
        package: dist/Frontend  # This should match your Angular build output folder
